version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: task-tracker-db
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: task-tracker-app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/task_tracker
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: 0123456789012345678901234567890123456789012345678901234567890123
    ports:
      - "8080:8080"
volumes:
  pgdata:
